import Head from "next/head";
import styles from "./index.module.scss";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  function toggleDarkMode() {
    setDarkMode(!darkMode);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>
            <div>
              <button onClick={toggleDarkMode} className={darkMode ? styles.dark : styles.light}>
                <div></div>
              </button>
            </div>
            <div>
              <span>6,291÷5</span>
            </div>
            <div>
              <span>1,258.2</span>
            </div>
          </div>
          <div>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
            <button></button>
          </div>
          <div>
            <div></div>
          </div>
        </div>
      </main>
    </>
  );
}
